---
name: merge dependabot

on:
  workflow_run:
    types:
    - completed
    workflows:
    - 'build'

jobs:
  merge:
    name: 'merge dependabot'
    runs-on: ubuntu-latest

    permissions:
      checks: read
      pull-requests: write
      statuses: read

    steps:
    - if: ${{ github.event.workflow_run.conclusion == 'success' }}
      name: merge
      uses: ridedott/merge-me-action@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_METHOD: MERGE
        ENABLE_GITHUB_API_PREVIEW: true
